# -*- coding: utf-8 -*-
"""recommendations

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1723tMlP-QW_2Py87hBasG7rhOkjjfNNE
"""

def generate_insights(rules):

    insights = []

    top_rules = rules.sort_values(
        "lift",
        ascending=False
    ).head(5)

    for _, r in top_rules.iterrows():

        antecedent = ", ".join(list(r["antecedents"]))
        consequent = ", ".join(list(r["consequents"]))

        insight = f"""
Customers who buy {antecedent}
are {round(r['lift'],2)}x more likely to buy {consequent}.
Confidence: {round(r['confidence'],2)}
"""

        insights.append(insight)

    return insights