# -*- coding: utf-8 -*-
"""recommendations

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1723tMlP-QW_2Py87hBasG7rhOkjjfNNE
"""

def optimize_layout(rules):

    recs=[]

    top_rules = rules.sort_values(
        by="lift",
        ascending=False
    ).head(10)

    for _,r in top_rules.iterrows():

        a=", ".join(list(r["antecedents"]))
        c=", ".join(list(r["consequents"]))

        rec=f"Place {a} near {c} (Lift {round(r['lift'],2)})"

        recs.append(rec)

    return recs