# -*- coding: utf-8 -*-
"""mba_engine

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1723tMlP-QW_2Py87hBasG7rhOkjjfNNE
"""

from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules

def run_mba(basket, support, confidence):

    itemsets = apriori(
        basket,
        min_support=support,
        use_colnames=True
    )

    rules = association_rules(
        itemsets,
        metric="confidence",
        min_threshold=confidence
    )

    return rules