# -*- coding: utf-8 -*-
"""recommendations

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1723tMlP-QW_2Py87hBasG7rhOkjjfNNE
"""

import networkx as nx
import plotly.graph_objects as go

def build_network(rules):

    G = nx.Graph()

    for _, row in rules.head(20).iterrows():

        a = list(row["antecedents"])[0]
        c = list(row["consequents"])[0]

        G.add_edge(a,c)

    pos = nx.spring_layout(G)

    edge_x = []
    edge_y = []

    for edge in G.edges():

        x0,y0 = pos[edge[0]]
        x1,y1 = pos[edge[1]]

        edge_x += [x0,x1,None]
        edge_y += [y0,y1,None]

    edge_trace = go.Scatter(x=edge_x,y=edge_y,mode='lines')

    node_x=[]
    node_y=[]

    for node in G.nodes():

        x,y = pos[node]

        node_x.append(x)
        node_y.append(y)

    node_trace = go.Scatter(
        x=node_x,
        y=node_y,
        mode='markers+text',
        text=list(G.nodes())
    )

    fig = go.Figure(data=[edge_trace,node_trace])

    return fig