# -*- coding: utf-8 -*-
"""preprocessing

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1723tMlP-QW_2Py87hBasG7rhOkjjfNNE
"""

import pandas as pd

def create_basket(df):

    basket = (
        df.groupby(['TransactionID','Item'])['Item']
        .count()
        .unstack()
        .fillna(0)
    )

    basket = basket.applymap(lambda x: 1 if x > 0 else 0)

    return basket