# -*- coding: utf-8 -*-
"""recommendations

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1723tMlP-QW_2Py87hBasG7rhOkjjfNNE
"""

def recommend_products(product, rules):

    rec = rules[
        rules['antecedents'].apply(lambda x: product in x)
    ]

    return rec[['antecedents','consequents','confidence','lift']]
