# -*- coding: utf-8 -*-
"""recommendations

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1723tMlP-QW_2Py87hBasG7rhOkjjfNNE
"""

from sklearn.cluster import KMeans

def run_segmentation(customer_matrix):

    kmeans = KMeans(n_clusters=4)

    clusters = kmeans.fit_predict(customer_matrix)

    customer_matrix["Segment"] = clusters

    return customer_matrix