# -*- coding: utf-8 -*-
"""recommendations

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1723tMlP-QW_2Py87hBasG7rhOkjjfNNE
"""

import pandas as pd

def next_product_prediction(df, product):

    transitions=[]

    transactions=df.groupby("TransactionID")["Item"].apply(list)

    for items in transactions:

        for i in range(len(items)-1):

            if items[i]==product:
                transitions.append(items[i+1])

    pred=pd.Series(transitions).value_counts().head(5)

    return pred