# -*- coding: utf-8 -*-
"""visualizations

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1723tMlP-QW_2Py87hBasG7rhOkjjfNNE
"""

import plotly.express as px

def plot_rule_scatter(rules):

    fig = px.scatter(
        rules,
        x="support",
        y="confidence",
        size="lift",
        color="lift",
        hover_data=["antecedents","consequents"]
    )

    return fig


def plot_3d_rules(rules):

    fig = px.scatter_3d(
        rules,
        x="support",
        y="confidence",
        z="lift",
        color="lift",
        hover_data=["antecedents","consequents"]
    )

    return fig