# -*- coding: utf-8 -*-
"""recommendations

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1723tMlP-QW_2Py87hBasG7rhOkjjfNNE
"""

import streamlit as st
import pandas as pd

from modules.dataset_generator import generate_dataset
from modules.preprocessing import create_basket
from modules.mba_engine import run_mba
from modules.visualization import plot_rule_scatter, plot_3d_rules
from modules.recommendation import recommend_products
from modules.insight_generator import generate_insights
from modules.network_graph import build_network
from modules.sequential_patterns import next_product_prediction
from modules.layout_optimizer import optimize_layout

st.set_page_config(layout="wide")

st.title("Retail Analytics & Market Basket Intelligence Lab")

support = st.sidebar.slider("Support",0.01,0.5,0.05)
confidence = st.sidebar.slider("Confidence",0.1,1.0,0.3)

file = st.sidebar.file_uploader("Upload dataset")

if file:
    df = pd.read_csv(file)

elif st.sidebar.button("Generate Dataset"):
    df = generate_dataset()

else:
    st.stop()

st.subheader("Dataset")
st.dataframe(df.head())

basket = create_basket(df)

rules = run_mba(basket,support,confidence)

st.subheader("Association Rules")
st.dataframe(rules)

st.subheader("Rule Dashboard")
st.plotly_chart(plot_rule_scatter(rules),use_container_width=True)

st.subheader("3D Rule Visualization")
st.plotly_chart(plot_3d_rules(rules),use_container_width=True)

product_list=list(basket.columns)

product=st.selectbox("Select Product",product_list)

st.subheader("Recommendations")

st.dataframe(
recommend_products(product,rules)
)

st.subheader("Retail Insights")

insights=generate_insights(rules)

for i in insights:
    st.write(i)

st.subheader("Product Network")

st.plotly_chart(build_network(rules))

st.subheader("Next Product Prediction")

st.bar_chart(
next_product_prediction(df,product)
)

st.subheader("Store Layout Optimization")

layout=optimize_layout(rules)

for r in layout:
    st.write(r)